### ISSUE TITLE
fsnotify event never matches on macOS [go v1.11]

### ISSUE THREAD

**Issue by msokk** [Teamwork/reload#2]
Hi,

With the latest go, `go build` triggers `REMOVE` + `CREATE` events in the fsnotify listener instead of `WRITE`. So it never triggers reload.

I don't know if it is related to 1.11.

**Comment by arp242** [comment]
It seems to work well for me with both Go 1.10 and 1.11; so I think it may be an macOS thing.

Could you apply the below patch and post the output from that after you do a `go build` or `go install`?

It seems curious that it doesn't trigger a `WRITE` at all, since it does need to actually write data to the file; but perhaps this is an macOS/kqueue thing?

```
diff --git i/reload.go w/reload.go
index c6b6ef6..ae65e55 100644
--- i/reload.go
+++ w/reload.go
@@ -58,6 +58,8 @@ func Do(log func(string, ...interface{})) error {
                                // Panic, and Fatal :-/ Printf() is probably best.
                                log("reload error: %v", err)
                        case event := <-watcher.Events:
+                               fmt.Printf("%s: %v\n", event.Name, event.Op)
+
                                if event.Op&fsnotify.Write == fsnotify.Write && event.Name == bin {
                                        // Wait for writes to finish.
                                        time.Sleep(100 * time.Millisecond)
```

For reference, this is what I have on my Linux system (Go 1.11):
```
$ go install
/home/martin/work/bin/hub-go-tmp-umask: REMOVE
/home/martin/work/bin/hub: REMOVE
/home/martin/work/bin/hub: CREATE
/home/martin/work/bin/hub: WRITE

$ go build
/home/martin/work/src/github.com/teamwork/hub/hub-go-tmp-umask: REMOVE
/home/martin/work/src/github.com/teamwork/hub/hub: REMOVE
/home/martin/work/src/github.com/teamwork/hub/hub: CREATE
/home/martin/work/src/github.com/teamwork/hub/hub: WRITE
```

**Comment by msokk** [comment]
```
$ go install
INFO[0000] restarting "/Users/mihkel/go/bin/atelier-api" when it changes
/Users/mihkel/go/bin/atelier-api: REMOVE
/Users/mihkel/go/bin/atelier-api: CREATE

$ go build
INFO[0000] restarting "/Users/mihkel/go/src/atelier-api/atelier-api" when it changes
/Users/mihkel/go/src/atelier-api/atelier-api: REMOVE
/Users/mihkel/go/src/atelier-api/atelier-api: CREATE
```

No `WRITE` at all on build or install, only when I edit file and save in VSCode:
```
/Users/mihkel/go/src/atelier-api/main.go: CHMOD
/Users/mihkel/go/src/atelier-api/main.go: WRITE
/Users/mihkel/go/src/atelier-api/main.go: CHMOD
```
Either fsnotify kqueue bug or expected behaviour.

**Comment by arp242** [comment]
Hm, interesting. You also don't have the `*-go-tmp-umask` file being created, but as I [understand the code](https://github.com/golang/go/blob/master/src/cmd/go/internal/work/exec.go#L1513-L1519) that should always get created.

I don't have a macOS machine to test this myself though. I could try a FreeBSD or OpenBSD VM maybe.

**Comment by msokk** [comment]
I haven't seen `*-go-tmp-umask` yet, looks like that install code you pasted has bunch of returns with conditions before, so it might never reach that point on macOS.

I tried it out on a bit older Macbook with Sierra + HFS + 1.10 go, still no `WRITE`.
The first logs were from High Sierra + APFS filesystem + 1.11.

I now noticed that Linux also has `REMOVE` + `CREATE` before `WRITE`.

**Comment by msokk** [comment]
https://github.com/fsnotify/fsnotify/issues/74 - events behaviour might totally be different between OS

I tried out creating a new text file with content with `nano`:
```
/Users/mihkel/go/src/atelier-api/test: CREATE
/Users/mihkel/go/src/atelier-api/test: CHMOD
```

and later editing it:
```
/Users/mihkel/go/src/atelier-api/test: CHMOD
/Users/mihkel/go/src/atelier-api/test: WRITE
/Users/mihkel/go/src/atelier-api/test: CHMOD
```

So I think there might never be a `WRITE` event on mac. 

Would you accept PR which adds a branch that only checks `CREATE` on `runtime.GOOS == "darwin"`?

**Comment by arp242** [comment]
> Would you accept PR which adds a branch that only checks `CREATE` on `runtime.GOOS == "darwin"`?

Sounds good; thanks for your research!

I wonder if `Create` means "file descriptor created" or "file created and written". I guess that the `time.Sleep(100 * time.Millisecond)` would take care of that, in case it's not written yet (...but it's not pretty).
